   # AWS_ACCESS_KEY_ID="AKIAZI2LE2Z6CLDSGQZ7"
   # AWS_SECRET_ACCESS_KEY="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"
   # AWS_DEFAULT_REGION="us-east-1"

variable "AWS_ACCESS_KEY_ID" {}
variable "AWS_SECRET_ACCESS_KEY" {}
variable "AWS_DEFAULT_REGION" {}
